### PR TITLE
assert: Fix NilError, error non-nil type

### LINKED ISSUE #185: Typed nil errors should not pass "NilError"
I don't think the fix for #167 (#171) was entirely correct. A typed `nil` error is not a `nil` error when compared against `nil` in a normal context.

```go
package baderr

import (
	"testing"

	"gotest.tools/v3/assert"
)

type myEvilError struct{}

func (m *myEvilError) Error() string {
	return "this is an error"
}

func doSomething() error {
	var err *myEvilError
	return err // NOT nil, this has a type.
}

// Should not pass.
func TestErrorNil(t *testing.T) {
	assert.NilError(t, doSomething()) // This says it's nil.
}

func TestErrorNotNil(t *testing.T) {
	assert.Assert(t, doSomething() != nil) // An actual comparison says it's not nil.
}
```

### LINKED ISSUE #186: "reflect: call of reflect.Value.IsNil on struct Value" for struct error type
The following code panics, as `NilError` is attempting to check `IsNil` on a non-pointer struct:

```
type structError struct{}

func (structError) Error() string {
	return "this is structError"
}

func TestStructError(t *testing.T) {
	var err error = structError{}
	assert.NilError(t, err)
}
```

```
--- FAIL: TestStructError (0.00s)
panic: reflect: call of reflect.Value.IsNil on struct Value [recovered]
	panic: reflect: call of reflect.Value.IsNil on struct Value

goroutine 21 [running]:
testing.tRunner.func1(0xc000110300)
	/usr/lib/go/src/testing/testing.go:874 +0x3a3
panic(0x59a640, 0xc000096120)
	/usr/lib/go/src/runtime/panic.go:679 +0x1b2
reflect.Value.IsNil(...)
	/usr/lib/go/src/reflect/value.go:1073
gotest.tools/v3/assert.assert(0x60d4c0, 0xc000110300, 0xc00007ef00, 0x5dec38, 0x5a0360, 0x748a08, 0x0, 0x0, 0x0, 0x0)
	/home/jake/go/pkg/mod/gotest.tools/v3@v3.0.1/assert/assert.go:123 +0x773
gotest.tools/v3/assert.NilError(0x60d4c0, 0xc000110300, 0x609d80, 0x748a08, 0x0, 0x0, 0x0)
	/home/jake/go/pkg/mod/gotest.tools/v3@v3.0.1/assert/assert.go:249 +0x101
some.tld/baderr.TestStructError(0xc000110300)
	/home/jake/testproj/baderr/err_test.go:36 +0x60
testing.tRunner(0xc000110300, 0x5df150)
	/usr/lib/go/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	/usr/lib/go/src/testing/testing.go:960 +0x350
FAIL	some.tld/baderr	0.009s
FAIL
```

The struct doesn't need to be empty; it can have values. Related to #167/#171.

However, I think #171 needs to be reverted anyway (#185), because a typed nil error is not "nil".

### PR DESCRIPTION
**Pull request by dnephin**
The previous fix in #171 incorrectly reported non-nil types as nil errors.
Instead this commit handles the case by using a different error message.

Fixes #185 
Fixes #186

### CODE REVIEW

File: assert/assert.go [hunk 1]
```diff
@@ -179,6 +175,15 @@ func logFailureFromBool(t TestingT, msgAndArgs ...interface{}) {
 	t.Log(format.WithCustomMessage(failureMessage+msg, msgAndArgs...))
 }
 
+func failureMsgFromError(err error) string {
+	// Handle errors with non-nil types
+	v := reflect.ValueOf(err)
+	if v.Kind() == reflect.Ptr && v.IsNil() {
+		return fmt.Sprintf("error is not nil: error has type %T", err)
```
Comment (zikaeroh) [inline assert/assert.go]: I still think that this could include the message if the call doesn't fail (https://github.com/gotestyourself/gotest.tools/issues/185#issuecomment-582745881), since calls on nil are valid so long as the method doesn't try and access its receiver as though it's not nil. A further improvement, though, and not strictly necessary to fix the other issues.

Comment (dnephin) [reply assert/assert.go]: That is true. I suspect that most `error` implementations which use a pointer receiver will require it to be non-nil. I would generally like to avoid the panic/recover, so would prefer to not add it for such a rare case, but it could be done as a future improvement.

**Comment by dnephin** [comment]
tagged v3.0.2 with this fix
