### PR TITLE
Handle symlinks in `fs.FromDir`

### LINKED ISSUE #103: `fs.FromDir` can fail during copy
If the folder we want to *copy from* contains weird files like dead link, it can error out.
I feel we should make it possible to pass options to `FromDir` like `ignoreDeadLink` or something like that.

cc @dnephin wdyt ?

### PR DESCRIPTION
**Pull request by vdemeester**
For any symlinks, it will *re-create* them the same way they were in
the source file instead of trying to read them and copy them as file.

This should fix errors when doing a `fs.FromDir` that contains dead link.

Closes #103

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

### CODE REVIEW

File: fs/ops.go [hunk 1]
```diff
@@ -181,14 +181,26 @@ func copyDirectory(source, dest string) error {
 			}
 			continue
 		}
-		// TODO: handle symlinks
-		if err := copyFile(sourcePath, destPath); err != nil {
+		if entry.Mode()&os.ModeSymlink != 0 {
+			if err := copySymLink(sourcePath, destPath); err != nil {
+				return err
+			}
+		} else if err := copyFile(sourcePath, destPath); err != nil {
```
Comment (dnephin) [inline fs/ops.go]: nit: I don't think we need the `else if`. It can `continue` in the success case. Alternatively it could use a switch/case.
